version: "3.4"

x-backend-variables: &backend-variables
  SECRET_KEY: ${SECRET_KEY:?}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD:?}
  REDIS_PASSWORD: ${REDIS_PASSWORD:?}
  BASEROW_JWT_SIGNING_KEY: ${BASEROW_JWT_SIGNING_KEY:-}
  BASEROW_PUBLIC_URL: https://baserow.nordikforge.com
  DATABASE_USER: ${DATABASE_USER:-baserow}
  DATABASE_NAME: ${DATABASE_NAME:-baserow}
  DATABASE_HOST: db
  REDIS_HOST: redis
  MIGRATE_ON_STARTUP: ${MIGRATE_ON_STARTUP:-true}
  SYNC_TEMPLATES_ON_STARTUP: ${SYNC_TEMPLATES_ON_STARTUP:-true}
  PRIVATE_BACKEND_URL: http://backend:8000

services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    environment:
      BASEROW_CADDY_ADDRESSES: ":80"
      PRIVATE_WEB_FRONTEND_URL: http://web-frontend:3000
      PRIVATE_BACKEND_URL: http://backend:8000
      BASEROW_PUBLIC_URL: https://baserow.nordikforge.com
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - media:/baserow/media
      - caddy_config:/config
      - caddy_data:/data
    networks:
      - internal
      - web_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.baserow-src.rule=Host(`baserow.nordikforge.com`)"
      - "traefik.http.routers.baserow-src.entrypoints=websecure"
      - "traefik.http.routers.baserow-src.tls.certresolver=myresolver"
      - "traefik.http.services.baserow-src.loadbalancer.server.port=80"
      - "traefik.docker.network=web_network"

  backend:
    image: baserow/backend:2.0.6
    restart: unless-stopped
    environment:
      <<: *backend-variables
    depends_on:
      - db
      - redis
    volumes:
      - media:/baserow/media
    networks:
      - internal

  web-frontend:
    image: baserow/web-frontend:2.0.6
    restart: unless-stopped
    environment:
      BASEROW_PUBLIC_URL: https://baserow.nordikforge.com
      PRIVATE_BACKEND_URL: http://backend:8000
    depends_on:
      - backend
    networks:
      - internal

  celery:
    image: baserow/backend:2.0.6
    restart: unless-stopped
    environment:
      <<: *backend-variables
    command: celery-worker
    depends_on:
      - backend
    volumes:
      - media:/baserow/media
    networks:
      - internal

  celery-export-worker:
    image: baserow/backend:2.0.6
    restart: unless-stopped
    command: celery-exportworker
    environment:
      <<: *backend-variables
    depends_on:
      - backend
    volumes:
      - media:/baserow/media
    networks:
      - internal

  celery-beat-worker:
    image: baserow/backend:2.0.6
    restart: unless-stopped
    command: celery-beat
    environment:
      <<: *backend-variables
    depends_on:
      - backend
    volumes:
      - media:/baserow/media
    networks:
      - internal

  db:
    image: pgvector/pgvector:pg15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DATABASE_USER:-baserow}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:?}
      - POSTGRES_DB=${DATABASE_NAME:-baserow}
    networks:
      - internal
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:?}
    networks:
      - internal

  volume-permissions-fixer:
    image: bash:4.4
    command: chown 9999:9999 -R /baserow/media
    volumes:
      - media:/baserow/media
    networks:
      - internal

volumes:
  pgdata:
  media:
  caddy_data:
  caddy_config:

networks:
  internal:
  web_network:
    external: true
